name: Build lncr-customer authorizer AWS Lambda 
on:
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - master 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      
      - name: Build with maven
        run: |
          cd aws-lambda/AuthorizerFunction
          mvn clean package test -DLNCR_OAUTH_SECRET_KEY=${{ secrets.LNCR_OAUTH_SECRET_KEY }}
        env:
          LNCR_OAUTH_SECRET_KEY: ${{ secrets.LNCR_OAUTH_SECRET_KEY }}

      - name: Upload JAR Artefact
        uses: actions/upload-artifact@v5
        with:
          name: lncr-custom-authorizer
          path: target/*.jar
